from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from gost_standardizer.core.presets import PRESETS, Preset, resolve_preset

KNOWN_TYPST_PATHS = [
    Path.home() / ".gemini" / "antigravity" / "bin" / "typst",
    Path.home() / ".cargo" / "bin" / "typst",
    Path("/usr/local/bin/typst"),
    Path("/usr/bin/typst"),
]


def find_typst_binary() -> str | None:
    """Find the path to the installed Typst binary."""
    env_path = os.environ.get("TYPST_PATH")
    if env_path and Path(env_path).is_file() and os.access(env_path, os.X_OK):
        return env_path

    which_path = shutil.which("typst")
    if which_path:
        return which_path

    for candidate in KNOWN_TYPST_PATHS:
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate)

    return None


def generate_gost_typst(
    preset_or_name: str | Preset | None = "report",
    title: str | None = None,
    author: str | None = None,
    organization: str | None = None,
    year: int | None = None,
    body_content: str | None = None,
) -> str:
    """Generate a GOST-compliant Typst template document."""
    preset: Preset
    if isinstance(preset_or_name, Preset):
        preset = preset_or_name
    else:
        preset = resolve_preset(preset_or_name or "report")

    import datetime
    current_year = year or datetime.date.today().year

    # Map preset metrics to Typst code
    margin_left = f"{preset.margin_left_mm}mm"
    margin_right = f"{preset.margin_right_mm}mm"
    margin_top = f"{preset.margin_top_mm}mm"
    margin_bottom = f"{preset.margin_bottom_mm}mm"
    font_size = f"{preset.body_font_size_pt}pt"
    font_name = preset.body_font_name
    indent = f"{preset.body_first_line_indent_mm}mm"

    # Leading for 1.5 line spacing in typst is approx 0.65em
    leading = "0.65em" if preset.body_line_spacing >= 1.4 else "0.5em"

    lines = [
        f"// Generated by gost-standardizer (Preset: {preset.title})",
        "",
        "#set document(",
        f'  title: "{title or "Документ по ГОСТ"}",',
        f'  author: "{author or "Автор"}",',
        ")",
        "",
        "#set page(",
        '  paper: "a4",',
        "  margin: (",
        f"    left: {margin_left},",
        f"    right: {margin_right},",
        f"    top: {margin_top},",
        f"    bottom: {margin_bottom},",
        "  ),",
        '  numbering: "1",',
        "  number-align: top + right,",
        ")",
        "",
        "#set text(",
        f'  font: ("{font_name}", "PT Astra Serif", "Liberation Serif", "DejaVu Serif"),',
        f"  size: {font_size},",
        '  lang: "ru",',
        ")",
        "",
        "#set par(",
        "  justify: true,",
        f"  leading: {leading},",
        f"  first-line-indent: {indent},",
        ")",
        "",
        "// GOST Headings formatting",
        "#show heading.where(level: 1): it => block(",
        f"  above: {preset.heading_space_before_pt}pt,",
        f"  below: {preset.heading_space_after_pt}pt,",
        ")[",
        "  #set align(center)",
        f"  #set text(weight: \"bold\", size: {preset.heading_font_size_pt}pt)",
        "  #upper(it.body)",
        "]",
        "",
        "#show heading.where(level: 2): it => block(",
        f"  above: {preset.heading_space_before_pt}pt,",
        f"  below: {preset.heading_space_after_pt}pt,",
        ")[",
        f"  #set text(weight: \"bold\", size: {preset.heading_font_size_pt}pt)",
        "  #it.body",
        "]",
        "",
        "#show heading.where(level: 3): it => block(",
        f"  above: {preset.heading_space_before_pt}pt,",
        f"  below: {preset.heading_space_after_pt}pt,",
        ")[",
        f"  #set text(weight: \"bold\", size: {preset.body_font_size_pt}pt)",
        "  #it.body",
        "]",
        "",
    ]

    # Title page logic
    if title:
        org_text = organization or "МИНИСТЕРСТВО НАУКИ И ВЫСШЕГО ОБРАЗОВАНИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ"
        lines.extend([
            "// --- Титульный лист (номер страницы не отображается) ---",
            "#page(numbering: none)[",
            "  #set align(center)",
            "  #set par(first-line-indent: 0mm, leading: 0.5em)",
            f'  #text(size: 11pt, weight: "regular")[{org_text}]',
            "  #v(5cm)",
            f'  #text(size: {preset.title_font_size_pt}pt, weight: "bold")[{title}]',
            "  #v(4cm)",
            "  #align(right)[",
            "    #block(width: 60%)[",
            "      #set align(left)",
            "      #set par(first-line-indent: 0mm, leading: 0.5em)",
            f"      *Выполнил:*\n      {author or 'Студент'}\n\n",
            "      *Проверил:*\n      Руководитель",
            "    ]",
            "  ]",
            "  #v(1fr)",
            f'  #text(size: 12pt)[г. Москва, {current_year}]',
            "]",
            "",
            "#counter(page).update(2)",
            "",
        ])

    if body_content:
        lines.append(body_content)
    else:
        lines.extend([
            "= ВВЕДЕНИЕ",
            "",
            "В данном разделе приводится вводная информация по теме работы, цели и задачи исследования.",
            "",
            "= ОСНОВНАЯ ЧАСТЬ",
            "",
            "Текст основной части документа, оформленный в строгом соответствии с требованиями ГОСТ.",
            "",
            "= ЗАКЛЮЧЕНИЕ",
            "",
            "Выводы по результатам проделанной работы.",
            "",
        ])

    return "\n".join(lines)


def _convert_markdown_table_to_typst(table_lines: list[str]) -> str:
    """Convert markdown table lines to Typst table syntax."""
    rows: list[list[str]] = []
    for line in table_lines:
        trimmed = line.strip().strip("|")
        # Check if delimiter row (e.g. :--- | ---:)
        if re.match(r"^[\s\-:|]+$", trimmed):
            continue
        cells = [c.strip() for c in trimmed.split("|")]
        rows.append(cells)

    if not rows:
        return ""

    num_cols = max(len(r) for r in rows)
    out = [f"#table(\n  columns: {num_cols},"]
    for row in rows:
        # pad row to num_cols
        padded = row + [""] * (num_cols - len(row))
        for cell in padded:
            # Inline markdown parsing for bold/italic in cell
            cell_fmt = re.sub(r"\*\*(.+?)\*\*", r"*\1*", cell)
            cell_fmt = re.sub(r"_(.+?)_", r"_\1_", cell_fmt)
            out.append(f"  [{cell_fmt}],")
    out.append(")")
    return "\n".join(out)


def markdown_to_gost_typst(
    markdown_text: str,
    preset_or_name: str | Preset | None = "report",
    title: str | None = None,
    author: str | None = None,
    organization: str | None = None,
    year: int | None = None,
) -> str:
    """Convert markdown text to GOST-compliant Typst document markup."""
    lines = markdown_text.splitlines()
    typst_body: list[str] = []

    in_code_block = False
    in_table = False
    table_lines: list[str] = []

    for line in lines:
        stripped = line.strip()

        # Code block fence
        if stripped.startswith("```"):
            if in_table:
                typst_body.append(_convert_markdown_table_to_typst(table_lines))
                table_lines = []
                in_table = False
            in_code_block = not in_code_block
            typst_body.append(line)
            continue

        if in_code_block:
            typst_body.append(line)
            continue

        # Markdown tables
        if stripped.startswith("|") and stripped.endswith("|"):
            in_table = True
            table_lines.append(line)
            continue
        elif in_table:
            typst_body.append(_convert_markdown_table_to_typst(table_lines))
            table_lines = []
            in_table = False

        # Headings
        heading_match = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading_match:
            depth = len(heading_match.group(1))
            h_text = heading_match.group(2).strip()
            typst_body.append(f"{'=' * depth} {h_text}")
            continue

        # Horizontal rule
        if re.match(r"^(\-{3,}|\*{3,}|_{3,})$", stripped):
            typst_body.append("#line(length: 100%, stroke: 0.5pt)")
            continue

        # Blockquote
        if stripped.startswith(">"):
            quote_text = stripped.lstrip(">").strip()
            typst_body.append(f"#quote(block: true)[{quote_text}]")
            continue

        # Ordered list
        ordered_match = re.match(r"^\d+\.\s+(.*)$", line)
        if ordered_match:
            item_text = ordered_match.group(1)
            item_text = re.sub(r"\*\*(.+?)\*\*", r"*\1*", item_text)
            typst_body.append(f"+ {item_text}")
            continue

        # Unordered list
        unordered_match = re.match(r"^[-*+]\s+(.*)$", line)
        if unordered_match:
            item_text = unordered_match.group(1)
            item_text = re.sub(r"\*\*(.+?)\*\*", r"*\1*", item_text)
            typst_body.append(f"- {item_text}")
            continue

        # Standard paragraph text formatting
        formatted = line
        # Convert links [text](url) -> #link("url")[text]
        formatted = re.sub(r"\[(.*?)\]\((.*?)\)", r'#link("\2")[\1]', formatted)
        # Bold **text** -> *text*
        formatted = re.sub(r"\*\*(.+?)\*\*", r"*\1*", formatted)

        typst_body.append(formatted)

    if in_table and table_lines:
        typst_body.append(_convert_markdown_table_to_typst(table_lines))

    body_content = "\n".join(typst_body)

    return generate_gost_typst(
        preset_or_name=preset_or_name,
        title=title,
        author=author,
        organization=organization,
        year=year,
        body_content=body_content,
    )


def compile_typst(
    input_path_or_content: str,
    output_path: str | None = None,
    root_dir: str | None = None,
) -> dict[str, Any]:
    """Compile Typst source code or .typ file into a PDF document."""
    binary = find_typst_binary()
    if not binary:
        raise RuntimeError("Typst binary is not installed or not found in PATH.")

    temp_typ: Path | None = None
    input_file: Path

    # Determine whether input is a file path or direct markup code
    candidate = Path(input_path_or_content)
    if candidate.is_file() or (len(input_path_or_content) < 400 and candidate.suffix == ".typ" and candidate.exists()):
        input_file = candidate
    else:
        # It's Typst source content: write to temporary file
        fd, tmp_name = tempfile.mkstemp(suffix=".typ", prefix="gost_typst_")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(input_path_or_content)
        temp_typ = Path(tmp_name)
        input_file = temp_typ

    out_file: Path
    if output_path:
        out_file = Path(output_path).resolve()
    else:
        out_file = input_file.with_suffix(".pdf")

    out_file.parent.mkdir(parents=True, exist_ok=True)

    cmd = [binary, "compile", str(input_file), str(out_file)]
    if root_dir:
        cmd.extend(["--root", str(root_dir)])

    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
        success = proc.returncode == 0 and out_file.exists()

        return {
            "success": success,
            "output_path": str(out_file) if success else None,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "error": None if success else (proc.stderr or f"Compilation failed with exit code {proc.returncode}"),
        }
    except Exception as exc:
        return {
            "success": False,
            "output_path": None,
            "stdout": "",
            "stderr": str(exc),
            "error": str(exc),
        }
    finally:
        if temp_typ and temp_typ.exists():
            try:
                temp_typ.unlink()
            except OSError:
                pass
